### PR TITLE
changed colours for dark theme

### PR DESCRIPTION
**Pull request by harperfect**

### CODE REVIEW

**Comment by toastal** [comment]
I think this is one of those tricky situations of black vs dark vs dim needing to be shoe-horned into `prefers-color-scheme: dark`. When I put this together, it was to look best on an OLED panels (the panel type for both my personal laptop and smart phone) where black is black and vibrant, contrast-y colors looked best.

On my displays now, it subjectively looks muddy--especially on my laptop since the background color is tainted with a warmer tone. The lower contrast is difficult to read when the panel is at a lower brightness value to conserve battery/energy. With the new colors, I find specifically `--Accent1-color`, `--Accent2-color`, and `--Highlight-kwb` hard to read on both my laptop and smart phone. I would suggest these values be brighter and/or more vibrant. 

For instance, previously using `#ef7f1a` on `#000` for hyperlinks was a AAA passing-grading rating on https://contrastchecker.com/ for calculating the WCAG contrast value ... which currently `#cf6f18` on `#201b1b` is only AA and a failing grade.

I might suggest retaining the previous values at least for [more contrast](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast) `@media screen and (prefers-color-scheme: dark) and (prefers-contrast: more)`.

**Comment by dmbaturin** [comment]
@toastal @harperfect's complaint was that the original dark theme was too hard on the eyes. I don't use it, but I tend to agree that the current version, on an ordinary laptop screen at least, is less so.

If you think we can't find a compromise that would suit everyone, could you make a PR for the `prefer-contrast` media query?

**Comment by toastal** [comment]
I'm not going to discount @harperfect's experience, I just find it curious that I have the exact opposite experience. I had to increase the brightness on devices above my preference for what I find optimal given the ambient light conditions in order to read it the documentation. I would be curious to know what @harperfect's setup was.

Ultimately most of this color scheme is a) subjective and b) subject to device and factors of one's environment. What feels to me as an objective issue is that hyperlinks, given that they are a part of the body text, *should* pass color contrast guidelines.

As for `prefer-contrast: more | less`, I could definitely do a merge a request given an further information provided by @harperfect 👍‍

**Comment by toastal** [comment]
https://github.com/settings/appearance

This explains why GitHub offers dark, high contrast dark, and dimmed dark. As much as I'd love Soupault to be as used as GitHub, it wouldn't warrant doing a *lot* of extra work -- especially since allowing the browser to give feedback about preferred contrast and color schemes is fingerprintable 😭

**Comment by dmbaturin** [comment]
@toastal @harperfect's complaint was that the original dark theme was too hard on the eyes. I don't use it, but I tend to agree that the current version, on an ordinary laptop screen at least, is less so.

If you think we can't find a compromise that would suit everyone, could you make a PR for the `prefer-contrast` media query?

**Pull request merged**
